spring.application.name=Aggregator
server.port=8086

spring.redis.host=localhost
spring.redis.port=6379

spring.cache.type=redis

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
management.endpoints.web.exposure.include=*

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
spring.cloud.openfeign.micrometer.enabled=true
spring.application.name=Aggregator


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://saiyam09.us.auth0.com/
spring.security.oauth2.resourceserver.jwt.audiences=http://localhost:8084
management.zipkin.tracing.enabled=false
# user service config circuit breaker 
resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.userService.sliding-window-type=COUNT_BASED


# hotel service config circuit breaker 
resilience4j.circuitbreaker.instances.hotelService.sliding-window-size=10
resilience4j.circuitbreaker.instances.hotelService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.hotelService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.hotelService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.hotelService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.hotelService.sliding-window-type=COUNT_BASED

# rating service config circuit breaker
resilience4j.circuitbreaker.instances.ratingService.sliding-window-size=10
resilience4j.circuitbreaker.instances.ratingService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ratingService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ratingService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.ratingService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.ratingService.sliding-window-type=COUNT_BASED

# retry config user
resilience4j.retry.instances.userService.max-attempts=3
resilience4j.retry.instances.userService.wait-duration=500ms
resilience4j.retry.instances.userService.enable-exponential-backoff=true
resilience4j.retry.instances.userService.exponential-backoff-multiplier=2

# retry config hotel
resilience4j.retry.instances.hotelService.max-attempts=3
resilience4j.retry.instances.hotelService.wait-duration=500ms
resilience4j.retry.instances.hotelService.enable-exponential-backoff=true
resilience4j.retry.instances.hotelService.exponential-backoff-multiplier=2

# retry config rating
resilience4j.retry.instances.ratingService.max-attempts=3
resilience4j.retry.instances.ratingService.wait-duration=500ms
resilience4j.retry.instances.ratingService.enable-exponential-backoff=true
resilience4j.retry.instances.ratingService.exponential-backoff-multiplier=2

# rate limiter userService
resilience4j.ratelimiter.instances.userService.limit-for-period=20
resilience4j.ratelimiter.instances.userService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.userService.timeout-duration=0

# rate Limiter ratingService
resilience4j.ratelimiter.instances.ratingService.limit-for-period=20
resilience4j.ratelimiter.instances.ratingService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.ratingService.timeout-duration=0

# rate limiter HotelService
resilience4j.ratelimiter.instances.hotelService.limit-for-period=20
resilience4j.ratelimiter.instances.hotelService.limit-refresh-period=1s
resilience4j.ratelimiter.instances.hotelService.timeout-duration=0




